# Generated by Django 4.1.13 on 2025-12-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
        ("appointments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="appointment_date",
            field=models.DateField(default="2025-01-01"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="appointment_time",
            field=models.TimeField(default="09:00"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="requested",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("doctor", "appointment_date", "appointment_time")},
        ),
    ]
