# Generated by Django 4.1.13 on 2025-12-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="gender",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
    ]
